name: fgsiz
description: "Fgsiz product catalog"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.5
  flutter_image_compress: ^2.2.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/
    - assets/products.json
    - assets/descriptions/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/static/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/OpenSans_Condensed-Medium.ttf
          weight: 500

  uses-material-design: true


